version: "3.5"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_PASSWORD: 11111111
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: productdb
    volumes:
      - ./db/mysql/mysql_data:/var/lib/mysql
    ports:
      - '8000:3308'
    networks:
      - vicky-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    networks:
      - vicky-network

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vicky
    image: product
    ports:
      - '8022:5000'
    tty: true
    volumes:
      - ./src:/app:rw
    networks:
      - vicky-network

networks:
  vicky-network:
    external:
     name: vicky-network